---

- name: git clone repository
  delegate_to: localhost
  become: false
  git:
    repo: "{{ grafana_dashboards_git_url }}"
    version: "{{ grafana_dashboards_git_version }}"
    dest: "{{ grafana_dashboards_dir }}"
    update: "{{ grafana_dashboards_git_update }}"

...
